name: Find New URLs

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  find_and_commit_urls:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run URL discovery script
        run: python find_urls.py
        continue-on-error: true

      - name: Commit urls.txt if changed
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add urls.txt
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: Add new URLs from discovery action"
            git push
          else
            echo "No changes to commit."
          fi
